### PR TITLE
Remove some functions from the public API

### PR DESCRIPTION
**Pull request by drzax**
This is a breaking change.

Is there any other API methods you'd consider removing @colingourlay?

### CODE REVIEW

**Comment by colingourlay** [comment]
I'd consider removing things like `isExactMount` and `isPrefixedMount` if we could enhance `isMount` with a 2nd argument of options, such as `{exact?: string, prefixed?: string}`, which supercharges the one function with the power of all 3. However, TS would start complaining if we tried to use the option-less form as a straight-up filter function (`elements.filter(isMount)`), because it doesn't match the `Array.prototype.filter` callback signature `(element, index, array, thisArg)`. I don't think it's too much of an ask to force us to rewrite those examples as `elements.filter(element => isMount(element))`, because that's what we'd have to do to pass the proposed exact/prefixed options anyway.

**Comment by drzax** [comment]
Cool — I'd actually started doing that already (and ran into the filter/map issue so stopped). If you're happy with that direction, I'll finish it off now.

**Comment by colingourlay** [comment]
Great! Go for it.

**Comment by drzax** [comment]
I'll merge and release a 2.0.0 if there are no objections.

**Comment by colingourlay** [comment]
Dooooo it!

**Pull request merged**
